name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration:
          - { vs: Release, make: release }
          - { vs: Debug, make: debug }

    runs-on: ${{ matrix.os }}

    env:
      VS_CONFIG: ${{ matrix.configuration.vs }}
      MAKE_CONFIG: ${{ matrix.configuration.make }}

    steps:
    - uses: actions/checkout@master
    - name: Setup premake
      uses: abel0b/setup-premake@v1

    # Linux & MacOS-specific build steps
    - name: Build (gmake2)
      if: runner.os != 'Windows'
      run: |
        premake5 gmake2
        make clean
        make all config=${MAKE_CONFIG}_x64
    - name: Test (gmake2)
      if: runner.os != 'Windows'
      run: ./bin/test

    # Windows-specific build steps
    - name: Add msbuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.1.0'
    - name: Build (vs2019)
      if: runner.os == 'Windows'
      run: |
        premake5 vs2019
        msbuild reliable.sln -nologo -m -t:Clean  -p:Configuration=$Env:VS_CONFIG
        msbuild reliable.sln -nologo -m -p:Configuration=$Env:VS_CONFIG
    - name: Test (vs2019)
      if: runner.os == 'Windows'
      run: "& ./bin/x64/$Env:VS_CONFIG/test.exe"